"""Initial migration

Revision ID: db3d46e06c3d
Revises: 
Create Date: 2025-11-14 23:52:15.746559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3d46e06c3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_id'), 'anomalies', ['id'], unique=False)
    op.create_index(op.f('ix_anomalies_region_id'), 'anomalies', ['region_id'], unique=False)
    op.create_index(op.f('ix_anomalies_tenant_id'), 'anomalies', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_anomalies_timestamp'), 'anomalies', ['timestamp'], unique=False)
    op.create_table('hospital_utilization_metrics',
    sa.Column('facility_id', sa.String(), nullable=True),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_utilization_metrics_facility_id'), 'hospital_utilization_metrics', ['facility_id'], unique=False)
    op.create_index(op.f('ix_hospital_utilization_metrics_id'), 'hospital_utilization_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_hospital_utilization_metrics_region_id'), 'hospital_utilization_metrics', ['region_id'], unique=False)
    op.create_index(op.f('ix_hospital_utilization_metrics_tenant_id'), 'hospital_utilization_metrics', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_hospital_utilization_metrics_timestamp'), 'hospital_utilization_metrics', ['timestamp'], unique=False)
    op.create_table('owid_covid_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('new_cases', sa.Float(), nullable=True),
    sa.Column('new_deaths', sa.Float(), nullable=True),
    sa.Column('hosp_patients', sa.Float(), nullable=True),
    sa.Column('icu_patients', sa.Float(), nullable=True),
    sa.Column('tests_per_thousand', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owid_covid_metrics_date'), 'owid_covid_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_owid_covid_metrics_id'), 'owid_covid_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_owid_covid_metrics_location'), 'owid_covid_metrics', ['location'], unique=False)
    op.create_table('pharmacy_aggregates',
    sa.Column('drug_category', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_aggregates_drug_category'), 'pharmacy_aggregates', ['drug_category'], unique=False)
    op.create_index(op.f('ix_pharmacy_aggregates_id'), 'pharmacy_aggregates', ['id'], unique=False)
    op.create_index(op.f('ix_pharmacy_aggregates_region_id'), 'pharmacy_aggregates', ['region_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_aggregates_tenant_id'), 'pharmacy_aggregates', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_aggregates_timestamp'), 'pharmacy_aggregates', ['timestamp'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('contributing_factors', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_id'), 'risk_scores', ['id'], unique=False)
    op.create_index(op.f('ix_risk_scores_region_id'), 'risk_scores', ['region_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_tenant_id'), 'risk_scores', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_timestamp'), 'risk_scores', ['timestamp'], unique=False)
    op.create_table('search_trends_metrics',
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('search_index', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_trends_metrics_id'), 'search_trends_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_search_trends_metrics_keyword'), 'search_trends_metrics', ['keyword'], unique=False)
    op.create_index(op.f('ix_search_trends_metrics_region_id'), 'search_trends_metrics', ['region_id'], unique=False)
    op.create_index(op.f('ix_search_trends_metrics_tenant_id'), 'search_trends_metrics', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_search_trends_metrics_timestamp'), 'search_trends_metrics', ['timestamp'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('risk_score_id', sa.Integer(), nullable=True),
    sa.Column('anomaly_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_region_id'), 'alerts', ['region_id'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.create_table('fund_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_score_id', sa.Integer(), nullable=True),
    sa.Column('allocated_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('allocation_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_allocations_id'), 'fund_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_fund_allocations_region_id'), 'fund_allocations', ['region_id'], unique=False)
    op.create_index(op.f('ix_fund_allocations_tenant_id'), 'fund_allocations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_fund_allocations_timestamp'), 'fund_allocations', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_allocations_timestamp'), table_name='fund_allocations')
    op.drop_index(op.f('ix_fund_allocations_tenant_id'), table_name='fund_allocations')
    op.drop_index(op.f('ix_fund_allocations_region_id'), table_name='fund_allocations')
    op.drop_index(op.f('ix_fund_allocations_id'), table_name='fund_allocations')
    op.drop_table('fund_allocations')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_region_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_search_trends_metrics_timestamp'), table_name='search_trends_metrics')
    op.drop_index(op.f('ix_search_trends_metrics_tenant_id'), table_name='search_trends_metrics')
    op.drop_index(op.f('ix_search_trends_metrics_region_id'), table_name='search_trends_metrics')
    op.drop_index(op.f('ix_search_trends_metrics_keyword'), table_name='search_trends_metrics')
    op.drop_index(op.f('ix_search_trends_metrics_id'), table_name='search_trends_metrics')
    op.drop_table('search_trends_metrics')
    op.drop_index(op.f('ix_risk_scores_timestamp'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_tenant_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_region_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_pharmacy_aggregates_timestamp'), table_name='pharmacy_aggregates')
    op.drop_index(op.f('ix_pharmacy_aggregates_tenant_id'), table_name='pharmacy_aggregates')
    op.drop_index(op.f('ix_pharmacy_aggregates_region_id'), table_name='pharmacy_aggregates')
    op.drop_index(op.f('ix_pharmacy_aggregates_id'), table_name='pharmacy_aggregates')
    op.drop_index(op.f('ix_pharmacy_aggregates_drug_category'), table_name='pharmacy_aggregates')
    op.drop_table('pharmacy_aggregates')
    op.drop_index(op.f('ix_owid_covid_metrics_location'), table_name='owid_covid_metrics')
    op.drop_index(op.f('ix_owid_covid_metrics_id'), table_name='owid_covid_metrics')
    op.drop_index(op.f('ix_owid_covid_metrics_date'), table_name='owid_covid_metrics')
    op.drop_table('owid_covid_metrics')
    op.drop_index(op.f('ix_hospital_utilization_metrics_timestamp'), table_name='hospital_utilization_metrics')
    op.drop_index(op.f('ix_hospital_utilization_metrics_tenant_id'), table_name='hospital_utilization_metrics')
    op.drop_index(op.f('ix_hospital_utilization_metrics_region_id'), table_name='hospital_utilization_metrics')
    op.drop_index(op.f('ix_hospital_utilization_metrics_id'), table_name='hospital_utilization_metrics')
    op.drop_index(op.f('ix_hospital_utilization_metrics_facility_id'), table_name='hospital_utilization_metrics')
    op.drop_table('hospital_utilization_metrics')
    op.drop_index(op.f('ix_anomalies_timestamp'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_tenant_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_region_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_id'), table_name='anomalies')
    op.drop_table('anomalies')
    # ### end Alembic commands ###

